# frozen_string_literal: true

require_relative 'charts/base'
require_relative 'charts/cartesian'
require_relative 'charts/line'
require_relative 'charts/area'
require_relative 'charts/bar'
require_relative 'charts/column'
require_relative 'charts/scatter'
require_relative 'charts/candlestick'
require_relative 'charts/range_bar'
require_relative 'charts/heatmap'
require_relative 'charts/bubble'
require_relative 'charts/radar'
require_relative 'charts/mixed'
require_relative 'charts/syncing'
require_relative 'charts/polar'
require_relative 'charts/pie'
require_relative 'charts/donut'
require_relative 'charts/radial_bar'
